import { ForumTopic, ForumComment } from './forumTypes'

export const mockTopics: ForumTopic[] = [
  {
    id: '1',
    title: 'Первый топик',
    content: 'Обсуждение игры',
    author: 'User1',
    createdAt: '2024-06-01',
    reactions: [
      {
        id: 'r1',
        emoji: '👍',
        count: 3,
        users: ['user2', 'user3', 'user4'],
      },
      {
        id: 'r2',
        emoji: '❤️',
        count: 2,
        users: ['user2', 'user5'],
      },
    ],
  },
  {
    id: '2',
    title: 'Вопросы по механике',
    content: 'Задавайте вопросы!',
    author: 'User2',
    createdAt: '2024-06-02',
    reactions: [
      {
        id: 'r3',
        emoji: '😂',
        count: 1,
        users: ['user1'],
      },
    ],
  },
  {
    id: '3',
    title: 'Любимые стратегии',
    content: 'Делимся тактиками и советами.',
    author: 'User3',
    createdAt: '2024-06-03',
    reactions: [
      {
        id: 'r4',
        emoji: '👏',
        count: 4,
        users: ['user1', 'user2', 'user4', 'user6'],
      },
      {
        id: 'r5',
        emoji: '🔥',
        count: 2,
        users: ['user2', 'user5'],
      },
    ],
  },
  {
    id: '4',
    title: 'Баги и предложения',
    content: 'Пишите, если нашли баг или есть идея!',
    author: 'User4',
    createdAt: '2024-06-04',
  },
  {
    id: '5',
    title: 'Оффтопик',
    content: 'Здесь можно поговорить о чём угодно.',
    author: 'User5',
    createdAt: '2024-06-05',
  },
  {
    id: '6',
    title: 'Скоро обновление!',
    content: 'Ждём новый патч!',
    author: 'User6',
    createdAt: '2024-06-06',
    reactions: [
      {
        id: 'r6',
        emoji: '🎉',
        count: 5,
        users: ['user1', 'user2', 'user3', 'user4', 'user5'],
      },
    ],
  },
  {
    id: '7',
    title: 'Любимые уровни',
    content: 'Делитесь любимыми картами.',
    author: 'User7',
    createdAt: '2024-06-07',
  },
  {
    id: '8',
    title: 'Скорость реакции',
    content: 'Как тренировать реакцию?',
    author: 'User8',
    createdAt: '2024-06-08',
  },
  {
    id: '9',
    title: 'Рекорды игроков',
    content: 'Пишите свои рекорды!',
    author: 'User9',
    createdAt: '2024-06-09',
  },
  {
    id: '10',
    title: 'FAQ',
    content: 'Часто задаваемые вопросы.',
    author: 'User10',
    createdAt: '2024-06-10',
  },
]

export const mockComments: ForumComment[] = [
  {
    id: 'c1',
    topicId: '1',
    content: 'Согласен, игра отличная!',
    author: 'User2',
    userId: 'user2',
    createdAt: '2024-06-01',
    reactions: [
      {
        id: 'rc1',
        emoji: '👍',
        count: 2,
        users: ['user1', 'user3'],
      },
    ],
  },
  {
    id: 'c2',
    topicId: '1',
    content: 'А какие есть секреты?',
    author: 'User3',
    userId: 'user3',
    createdAt: '2024-06-02',
    reactions: [
      {
        id: 'rc2',
        emoji: '😮',
        count: 1,
        users: ['user2'],
      },
    ],
  },
  {
    id: 'c3',
    topicId: '2',
    content: 'Какой максимальный уровень?',
    author: 'User1',
    userId: 'user1',
    createdAt: '2024-06-02',
  },
  {
    id: 'c4',
    topicId: '3',
    content: 'Я всегда стараюсь ловить яйца в правом верхнем углу!',
    author: 'User2',
    userId: 'user2',
    createdAt: '2024-06-03',
    reactions: [
      {
        id: 'rc3',
        emoji: '💯',
        count: 3,
        users: ['user1', 'user3', 'user4'],
      },
    ],
  },
  {
    id: 'c5',
    topicId: '1',
    content: 'Спасибо за ответы!',
    author: 'User4',
    userId: 'user4',
    createdAt: '2024-06-03',
  },
  {
    id: 'c6',
    topicId: '1',
    content: 'Очень интересная тема!',
    author: 'User5',
    userId: 'user5',
    createdAt: '2024-06-04',
  },
  {
    id: 'c7',
    topicId: '1',
    content: 'А кто сколько набирал очков?',
    author: 'User6',
    userId: 'user6',
    createdAt: '2024-06-05',
  },
  {
    id: 'c8',
    topicId: '1',
    content: 'Я больше 1000!',
    author: 'User7',
    userId: 'user7',
    createdAt: '2024-06-06',
    reactions: [
      {
        id: 'rc4',
        emoji: '🔥',
        count: 2,
        users: ['user2', 'user3'],
      },
    ],
  },
  {
    id: 'c9',
    topicId: '1',
    content: 'А я только учусь.',
    author: 'User8',
    userId: 'user8',
    createdAt: '2024-06-07',
  },
  {
    id: 'c10',
    topicId: '1',
    content: 'Всем удачи!',
    author: 'User9',
    userId: 'user9',
    createdAt: '2024-06-08',
  },
  {
    id: 'c11',
    topicId: '2',
    content: 'Спасибо за советы!',
    author: 'User10',
    userId: 'user10',
    createdAt: '2024-06-09',
  },
  {
    id: 'c12',
    topicId: '2',
    content: 'Очень помогло!',
    author: 'User1',
    userId: 'user1',
    createdAt: '2024-06-10',
  },
]
